[project]
name = "backend"
version = "0.1.0"
description = "Backend for checking parcel temperature safety"
authors = [
    { name = "mkan1ewski" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
